### ISSUE TITLE
Observing fonts not declared in CSS (Safari bug)

### ISSUE THREAD

**Issue by Monokai** [bramstein/fontfaceobserver#85] opened 2016-11-06 19:45 UTC
When observing a font that is not used anywhere on an HTML page, the promise resolves in Safari without the font actually being loaded. In Chrome this works fine: the font is loaded and the promise resolves after that.

In my case I'm only using a font in a canvas 2d context using `fillText()`, so I thought I wouldn't need the font declared for an HTML element at all.

The solution seems to be to declare the font in dummy CSS for any HTML element, but it would be nice if that wasn't necessary.

**Comment by bramstein** [comment] 2016-11-16 16:24
Do you have a test case for this? I'm having trouble reproducing it (though there seems to be some weirdness in Safari).

**Comment by bramstein** [comment] 2016-11-23 11:47
I think this is caused by a bug in Safari 10. I've opened a pull request with more detail: #86.

**Comment by bramstein** [comment] 2016-11-28 20:21
Could you try v2.0.6? I think it works around this issue.

**Comment by zenderol** [comment] 2016-11-28 20:24
@bramstein will do, thanks!

**Comment by Monokai** [comment] 2016-11-29 08:43
@bramstein Yes, it works fine now in Safari. I no longer have to declare the font in CSS when I'm only using it in a canvas context. Thanks.

**Comment by wardpeet** [comment] 2016-12-06 16:28
@bramstein I think you can close this

**Comment by diniscorreia** [comment] 2016-12-06 16:34
@bramstein yep, working fine now!

**Comment by bramstein** [comment] 2016-12-07 05:30
Thanks for confirming. Closing this issue.

**Closed by bramstein** 2016-12-07 05:30 UTC
Labels: bug
