### ISSUE TITLE
Flash of invisible text

### ISSUE THREAD

**Issue by rarkins** [bramstein/fontfaceobserver#11] opened 2015-03-21 08:09 UTC
I thought I'd just float this problem in case I'm not the only one who experienced this and someone else finds it in future (Closed or otherwise).

I implemented @scottjehl's [suggestion](http://www.filamentgroup.com/lab/font-events.html) for using this code for eliminating the FOIT caused by CSS parsing. Unfortunately, I needed to roll this back as my FOIT time *increased*. I didn't really have the time/resources to find the root cause so don't mind if you close this unsolved.

On a fast connection, I'd see perhaps a half second FOIT, and when slowing down using Chrome devtools throttling it could be in the multiple seconds. Here's what I know, in case it helps someone else or someone else can help me:

1. I was using two fonts
2. I tried both the standalone (with promises) approach as well as our own Q-based promise
3. The promises weren't firing immediately - they did seem to be waiting on *something*.
- The promises fired a little before the fonts showed (visually) as finished in dev tools network view. Also it seemed like the time the FOIT turned into visible text did coincide with devtools showing the fonts being present
- Problem was present on multiple devices and browsers
- I tried using both `check()` as well as `check(null, 10000)` and neither made a difference

One suspicion was that this FOIT coincided with the async loading (using `loadCSS`) of my bootstrap CSS file. The FOIT certainly seemed to happen at around the same time. However I removed all custom font references from it and still the problem persisted.

**Comment by bramstein** [comment] 2015-03-21 17:09
That sounds worrisome. Do you happen to have the code (or a test case) somewhere?

**Comment by bramstein** [comment] 2015-03-31 14:18
I think this problem was caused by a bug that is now fixed. Could you try the latest version and see if that gives you better results?

**Comment by rarkins** [comment] 2015-03-31 14:50
Sorry for missing your earlier question. I completely reverted the code I used previously, so can't quickly test again. Also as it's integrated into my webpack build, it's not particularly portable. However I'll see about branching and reimplementing it some time to check.

**Comment by bramstein** [comment] 2015-09-23 08:43
I'm closing this issue because it hasn't seen any activity since May. Feel free to re-open if this is still an issue.

**Closed by bramstein** 2015-09-23 08:43 UTC
