### ISSUE TITLE
IE9, IE11, EDGE not working

### ISSUE THREAD

**Issue by iondrimba** [bramstein/fontfaceobserver#97] opened 2017-04-05 12:25 UTC
Doing some tests in IE9 I noticed the fonts-loaded class won't be added on the html tag.
![captura de tela 2017-04-05 as 9 22 29 am](https://cloud.githubusercontent.com/assets/178548/24705296/a54df9de-19e1-11e7-939a-b71ab2f634de.png)

**Comment by bramstein** [comment] 2017-04-07 09:08
Thanks for the report. The Font Face Observer website does not work in IE9, but Font Face Observer itself should. Is it throwing any errors?

**Comment by iondrimba** [comment] 2017-04-07 10:45
No errors

**Comment by monolux** [comment] 2017-05-02 15:49
![windows 10 ie edge fontfaceobserver 001](https://cloud.githubusercontent.com/assets/5672418/25626366/9f620a90-2f5f-11e7-80da-bb89bd9fc4a0.png)
 Can confirm this, Edge on W10 does not show `fonts-loaded` on `html` tag.

**Comment by bramstein** [comment] 2017-05-22 08:20
I just ran my tests again: Font Face Observer (the library) works in IE8+. The Font Face Observer website (http://www.fontfaceobserver.com) does not, which is expected (and not the fault of the library).

I'm closing this issue, unless someone has a test case that shows the FFO library doesn't work in IE8/9/10/11.

**Closed by bramstein** 2017-05-22 08:20 UTC

**Comment by iondrimba** [comment] 2017-05-22 10:47
@bramstein Have you figured out why it doesn't work in the FFO website?

**Comment by dutchwebworks** [comment] 2017-07-17 13:18
@bramstein 

I also tested this in Win/IE10 and 11. Browsers that we still need to support. The FontFaceObserver JavaScript uses a promise() which is unsupported by Win/IE8+. Getting Win/IE console script errors: 'Promise' is undefined.

**Comment by tomByrer** [comment] 2017-07-17 13:47
> 'Promise' is undefined.

Needs to be polyfilled: http://caniuse.com/#feat=promises

**Comment by bramstein** [comment] 2017-07-17 17:01
There's a polyfill included with the default build: https://github.com/bramstein/fontfaceobserver/blob/master/fontfaceobserver.js

**Comment by alexkuzmin** [comment] 2018-07-06 08:43
It does not work in IE11. What I've done:
npm install
import in project with webpack: 'import FontFaceObserver from 'fontfaceobserver';' - as far I understand, the polyfill is already there. Then the code:

const handbookObserver = new FontFaceObserver('handbook', {});
        handbookObserver.load().then(function () {
            console.log('loaded');
        });

It works in all browsers except IE.

**Comment by dashifen** [comment] 2018-07-24 12:56
Can additionally confirm.  The promise polyfill is functional - if I pass two functions to the load() method of the FontFaceObserver object, the first one (the success case) never fires.  The latter one always fires.  I have waited as long as 30 second to see if it was a timing problem.  

Additionally, can confirm that the fonts are loaded despite what the observer says about the elements.  This is all in the current version of Edge.

One screen shot to show Font Awesome fonts in use on the site.  Second one to show that HTML element says they're unavailable.

<img width="92" alt="working" src="https://user-images.githubusercontent.com/8269/43139169-11aa6f00-8f1f-11e8-977a-f60e9bb017e6.png">
<img width="362" alt="not-working" src="https://user-images.githubusercontent.com/8269/43139170-11ba21de-8f1f-11e8-8a2f-86eca24a581d.png">

And, finally, here's the javascript I'm using:

```javascript
const FontFaceObserver = require("fontfaceobserver"),

	fonts = {
		"fontawesome-free": new FontFaceObserver("Font Awesome 5 Free"),
		"fontawesome-brands": new FontFaceObserver("Font Awesome 5 Brands"),
	};

for (let font in fonts) {
	if (fonts.hasOwnProperty(font)) {
		let observer = fonts[font];
		observer.load(null, 30000).then(function () {
			document.documentElement.classList.add(font + "-available");
		}, function () {
			document.documentElement.classList.add(font + "-unavailable");
		})
	}
}
````

**Comment by alexkuzmin** [comment] 2018-07-24 16:18
Because of IE11 problem I've switched to another library, WebFontLoader https://github.com/typekit/webfontloader, and configured it for custom fonts. It successfully works with IE11.

**Comment by dianasotirova** [comment] 2019-08-22 09:46
Hi,

we are experiencing the same problem. This issue exactly the same as described by @dashifen.

**Comment by d4rky-pl** [comment] 2019-10-10 08:02
It doesn't work properly with icon fonts, even if every other browser works just fine. 
Example: https://github.com/d4rky-pl/expo-web-broken-icons 
(this library is being used by Expo web support now which is why the example is for Expo but the issue is ultimately with this library)

**Comment by webstar** [comment] 2022-01-17 09:34
> It does not work in IE11. What I've done: npm install import in project with webpack: 'import FontFaceObserver from 'fontfaceobserver';' - as far I understand, the polyfill is already there. Then the code:
> 
> const handbookObserver = new FontFaceObserver('handbook', {}); handbookObserver.load().then(function () { console.log('loaded'); });
> 
> It works in all browsers except IE.

@alexkuzmin 
Looks to be because the default file when importing/requiring the library is actually the standalone version. I had to explicitly state the non-standalone version.

`var FontFaceObserver = require('fontfaceobserver/fontfaceobserver.js');`
