### ISSUE TITLE
fontfaceobserver prevents twitter widget on IE

### ISSUE THREAD

**Issue by Kilbourne** [bramstein/fontfaceobserver#30] opened 2015-09-01 14:53 UTC
Edit: the bug is caused by promis.js , not directly by fontfaceobserver.

try this simple test: www.menthalia.com/test-twitter-ie

**Comment by bramstein** [comment] 2015-09-03 12:32
The widget appears to load for me. What browser are you seeing problems in?

**Comment by Kilbourne** [comment] 2015-09-03 13:36
IE11 only( the only IE i've tested)

2015-09-03 14:32 GMT+02:00 Bram Stein <notifications@github.com>:

**Comment by bramstein** [comment] 2015-09-03 13:54
Sorry, I deleted my comment when I noticed the browser in the title. I managed to reproduce this. Looks like it is caused by an incompatibility between Promise polyfills. I suspect the `all` and `race` methods as the official test suite doesn't cover those.

**Comment by bramstein** [comment] 2015-09-23 06:58
This has been fixed in v1.5.2. Thanks a lot for reporting it and providing a test case.

**Closed by bramstein** 2015-09-23 06:58 UTC
